meta_title: "Azuréenne sécurité"
meta_description: "Société de sécurité et protection basée à Marseille. Bailleurs sociaux, syndics, Résidence, Hôtellerie, ERP, survillance des chantiers"
meta_image: "logo.png"